### ISSUE TITLE
property 'put' of undefined

### ISSUE THREAD

**Issue by MaartenProvo** [paldepind/synceddb#12]
Perhaps a stupid question, I get an error can not read property 'put' of undefined. But I can't find how to fix it, searched in the example files, but no clues there.

[Anamnese - Pc v4.html.txt](https://github.com/paldepind/synceddb/files/237892/Anamnese.-.Pc.v4.html.txt)
[DB-Ambu-4.js.txt](https://github.com/paldepind/synceddb/files/237893/DB-Ambu-4.js.txt)

**Comment by piglovesyou** [comment]
`syncedDB.open().then()` doesn't return `db`. So I guess this will work.

```
var db = syncedDB.open({
	name: 'Ambu-DB',
        // ...
});
db.then(function() {
	addPatients();
}).catch(function(err) {
	// ...
});
```

Or, because the argument of function passed to `SDBDatabase#then()` is [`{db: db, e: e}`](https://github.com/paldepind/synceddb/blob/68957b621babe3371a6b188ed02df3826474240a/client/synceddb.js#L454), I think you can use that too.

**Comment by piglovesyou** [comment]
@MaartenProvo Tell me even after the above answer.
